name: Lint and Test
on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5
            - name: Install Dependencies
              uses: npm ci
            - name: Lint
              run: npm run lint
            
            - name:  Test Code
              run: npm run test

            - name:  Build Code
              run: npm run build

